package com.example.demo;

import java.util.Objects;

    /*
    Junior developer wrote following code.
    Please review and fix all that deserve to be fixed
    */
    @SuppressWarnings("ALL")
    class Person {
        public String firstName;
        public String middleName;
        public String lastName;

        public Person(String firstName, String middleName, String lastName) {
            //class is not inheriting any class/interface
            super();
            this.firstName = firstName;
            this.middleName = middleName;
            this.lastName = lastName;
        }

        public Person(String lastName, String firstName) {
            //class is not inheriting any class/interface
            super();
            this.lastName = lastName;
            //middleName is not used as parameter in this constructer, can remove the below line
            this.middleName = null;
            this.firstName = firstName;
        }


        // Getters and setters for all of three fields were properly generated by IDE and thus omitted here


        public String getFullName() {
            return this.firstName + " " + this.middleName + " " + this.lastName;
        }

        public boolean equals(Person person) {
            //Optional<String> ifPresent()
            System.out.println("inside person : "+ person.firstName);
            return Objects.equals(this.firstName, person.firstName)
                    && Objects.equals(this.lastName, person.lastName);
        }

        public long hashCode(Person person) {

            int hashVal = Integer.MIN_VALUE;


            return (long) hashVal;
        }

        public static void main(String[] args) {
            Person p = new Person("J", "D");
            Integer i = new Integer(1);
            p.equals(i);
        }

    }
